version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/workspace/reelmail-backend/
hooks:
  AfterInstall:
    - location: scripts/start_pm2.sh
      timeout: 300
      runas: root
