version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/workspace/reelmail-backend/
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: scripts/start_pm2.sh
      timeout: 300
      runas: root

